# Generated by Django 3.0.6 on 2020-05-12 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Task Manager', 'Task Manager'), ('Task Member', 'Task Member')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50, null=True)),
                ('taskdesc', models.CharField(max_length=300, null=True)),
                ('target', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('startdate', models.DateTimeField(null=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('creatorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devcal.Duser')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.IntegerField(null=True)),
                ('fillupdate', models.DateTimeField(null=True)),
                ('fillerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devcal.Duser')),
                ('taskid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devcal.Task')),
            ],
        ),
    ]
