# Generated by Django 3.0.6 on 2020-05-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcal', '0003_duser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devcal.Duser')),
                ('taskid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devcal.Task')),
            ],
        ),
    ]
