# Generated by Django 3.0.6 on 2020-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcal', '0005_auto_20200513_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreport',
            name='fillupdate',
            field=models.DateField(null=True),
        ),
    ]
