# Generated by Django 3.0.6 on 2020-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcal', '0006_auto_20200513_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
