# Generated by Django 3.0.6 on 2020-05-14 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devcal', '0007_auto_20200513_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='duser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creatorid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='devcal.Duser'),
        ),
        migrations.AlterField(
            model_name='taskassign',
            name='taskid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskmembers', to='devcal.Task'),
        ),
    ]
