# Generated by Django 3.0.6 on 2020-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcal', '0008_auto_20200514_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
