# Generated by Django 3.0.6 on 2020-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcal', '0009_duser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
